<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\Patient;
use Illuminate\Database\Seeder;

/**
 * PatientSeeder
 *
 * Seeds 30 realistic breast cancer patients derived from TCGA-BRCA
 * clinical data patterns. All values are anonymised and representative
 * of real clinical distributions.
 *
 * Run: php artisan db:seed --class=PatientSeeder
 * Or add to DatabaseSeeder::run() after org/user setup.
 */
class PatientSeeder extends Seeder
{
    public function run(): void
    {
        // Find the first active organization to attach patients to
        $org = Organization::where('status', 'active')->first();

        if (!$org) {
            $this->command->warn('No active organization found. Skipping PatientSeeder.');
            return;
        }

        $patients = $this->getPatientData();

        $created = 0;
        foreach ($patients as $p) {
            // Skip if identifier already exists
            if (Patient::where('patient_identifier', $p['patient_identifier'])->exists()) {
                continue;
            }

            Patient::create([
                'organization_id'         => $org->id,
                'patient_identifier'      => $p['patient_identifier'],
                'er_status'               => $p['er_status'],
                'pr_status'               => $p['pr_status'],
                'her2_binary'             => $p['her2_binary'],
                'age'                     => $p['age'],
                'stage_num'               => $p['stage_num'],
                'er_status_missing'       => $p['er_status_missing'] ?? false,
                'pr_status_missing'       => $p['pr_status_missing'] ?? false,
                'fraction_genome_altered' => $p['fraction_genome_altered'] ?? null,
                'buffa_hypoxia_score'     => $p['buffa_hypoxia_score'] ?? null,
                'ragnum_hypoxia_score'    => $p['ragnum_hypoxia_score'] ?? null,
                'winter_hypoxia_score'    => $p['winter_hypoxia_score'] ?? null,
            ]);
            $created++;
        }

        $this->command->info("PatientSeeder: {$created} patients created for org '{$org->name}'.");
    }

    /**
     * 30 representative TCGA-BRCA style patients.
     * Mix of Luminal A (ER+/PR+/HER2-/low Ki67) and Non-Luminal A profiles.
     * Genomic scores are from published TCGA distributions.
     */
    private function getPatientData(): array
    {
        return [
            // ── Luminal A profiles (ER+, PR+, HER2-, low stage) ──────────────
            [
                'patient_identifier'      => 'TCGA-E2-A1IU',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 58,
                'stage_num'               => 1,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.04,
                'buffa_hypoxia_score'     => -3.21,
                'ragnum_hypoxia_score'    => -2.87,
                'winter_hypoxia_score'    => -4.12,
            ],
            [
                'patient_identifier'      => 'TCGA-A2-A0YM',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 63,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.07,
                'buffa_hypoxia_score'     => -2.94,
                'ragnum_hypoxia_score'    => -2.51,
                'winter_hypoxia_score'    => -3.78,
            ],
            [
                'patient_identifier'      => 'TCGA-BH-A0BZ',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 47,
                'stage_num'               => 1,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.03,
                'buffa_hypoxia_score'     => -4.05,
                'ragnum_hypoxia_score'    => -3.62,
                'winter_hypoxia_score'    => -5.01,
            ],
            [
                'patient_identifier'      => 'TCGA-D8-A1JD',
                'er_status'               => true,
                'pr_status'               => false,
                'her2_binary'             => false,
                'age'                     => 71,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.12,
                'buffa_hypoxia_score'     => -1.88,
                'ragnum_hypoxia_score'    => -1.44,
                'winter_hypoxia_score'    => -2.33,
            ],
            [
                'patient_identifier'      => 'TCGA-AO-A12F',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 54,
                'stage_num'               => 1,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.05,
                'buffa_hypoxia_score'     => -3.67,
                'ragnum_hypoxia_score'    => -3.14,
                'winter_hypoxia_score'    => -4.55,
            ],
            [
                'patient_identifier'      => 'TCGA-C8-A12L',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 66,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.09,
                'buffa_hypoxia_score'     => -2.45,
                'ragnum_hypoxia_score'    => -2.01,
                'winter_hypoxia_score'    => -3.12,
            ],
            [
                'patient_identifier'      => 'TCGA-E9-A1N4',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 52,
                'stage_num'               => 1,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.06,
                'buffa_hypoxia_score'     => -3.89,
                'ragnum_hypoxia_score'    => -3.41,
                'winter_hypoxia_score'    => -4.78,
            ],
            [
                'patient_identifier'      => 'TCGA-GM-A2DA',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 44,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.08,
                'buffa_hypoxia_score'     => -2.78,
                'ragnum_hypoxia_score'    => -2.34,
                'winter_hypoxia_score'    => -3.56,
            ],
            [
                'patient_identifier'      => 'TCGA-A8-A07Z',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 60,
                'stage_num'               => 1,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.04,
                'buffa_hypoxia_score'     => -4.22,
                'ragnum_hypoxia_score'    => -3.88,
                'winter_hypoxia_score'    => -5.14,
            ],
            [
                'patient_identifier'      => 'TCGA-BH-A18V',
                'er_status'               => true,
                'pr_status'               => false,
                'her2_binary'             => false,
                'age'                     => 75,
                'stage_num'               => 3,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.18,
                'buffa_hypoxia_score'     => -0.92,
                'ragnum_hypoxia_score'    => -0.55,
                'winter_hypoxia_score'    => -1.23,
            ],
            // ── Luminal A — DZ mode (no genomics) ────────────────────────────
            [
                'patient_identifier'      => 'DZ-CONST-001',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 49,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            [
                'patient_identifier'      => 'DZ-ORAN-002',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 55,
                'stage_num'               => 1,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            [
                'patient_identifier'      => 'DZ-ALGER-003',
                'er_status'               => true,
                'pr_status'               => false,
                'her2_binary'             => false,
                'age'                     => 62,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            [
                'patient_identifier'      => 'DZ-ANNABA-004',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 41,
                'stage_num'               => 1,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            [
                'patient_identifier'      => 'DZ-SETIF-005',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 68,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            // ── Non-Luminal A profiles (HER2+ or ER-/PR-) ────────────────────
            [
                'patient_identifier'      => 'TCGA-A2-A0T2',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => true,
                'age'                     => 45,
                'stage_num'               => 3,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.38,
                'buffa_hypoxia_score'     => 2.14,
                'ragnum_hypoxia_score'    => 1.87,
                'winter_hypoxia_score'    => 2.56,
            ],
            [
                'patient_identifier'      => 'TCGA-BH-A0C1',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => false,
                'age'                     => 38,
                'stage_num'               => 3,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.52,
                'buffa_hypoxia_score'     => 3.45,
                'ragnum_hypoxia_score'    => 2.98,
                'winter_hypoxia_score'    => 4.12,
            ],
            [
                'patient_identifier'      => 'TCGA-E2-A14Z',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => true,
                'age'                     => 51,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.29,
                'buffa_hypoxia_score'     => 1.67,
                'ragnum_hypoxia_score'    => 1.34,
                'winter_hypoxia_score'    => 2.01,
            ],
            [
                'patient_identifier'      => 'TCGA-D8-A27N',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => false,
                'age'                     => 42,
                'stage_num'               => 4,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.61,
                'buffa_hypoxia_score'     => 4.23,
                'ragnum_hypoxia_score'    => 3.78,
                'winter_hypoxia_score'    => 5.01,
            ],
            [
                'patient_identifier'      => 'TCGA-A7-A0CE',
                'er_status'               => true,
                'pr_status'               => false,
                'her2_binary'             => true,
                'age'                     => 57,
                'stage_num'               => 3,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.33,
                'buffa_hypoxia_score'     => 1.89,
                'ragnum_hypoxia_score'    => 1.52,
                'winter_hypoxia_score'    => 2.34,
            ],
            // ── Non-Luminal A — DZ mode ───────────────────────────────────────
            [
                'patient_identifier'      => 'DZ-BLIDA-006',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => true,
                'age'                     => 46,
                'stage_num'               => 3,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            [
                'patient_identifier'      => 'DZ-TIZI-007',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => false,
                'age'                     => 39,
                'stage_num'               => 3,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            [
                'patient_identifier'      => 'DZ-BEJAIA-008',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => true,
                'age'                     => 53,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            // ── Missing biomarker cases ───────────────────────────────────────
            [
                'patient_identifier'      => 'DZ-MSILA-009',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 59,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => true,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            [
                'patient_identifier'      => 'DZ-BATNA-010',
                'er_status'               => true,
                'pr_status'               => false,
                'her2_binary'             => false,
                'age'                     => 72,
                'stage_num'               => 3,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
            [
                'patient_identifier'      => 'TCGA-OL-A5RU',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 48,
                'stage_num'               => 1,
                'er_status_missing'       => true,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.06,
                'buffa_hypoxia_score'     => -3.44,
                'ragnum_hypoxia_score'    => -3.01,
                'winter_hypoxia_score'    => -4.22,
            ],
            [
                'patient_identifier'      => 'TCGA-LL-A5YO',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => false,
                'age'                     => 36,
                'stage_num'               => 4,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.71,
                'buffa_hypoxia_score'     => 5.12,
                'ragnum_hypoxia_score'    => 4.67,
                'winter_hypoxia_score'    => 6.23,
            ],
            [
                'patient_identifier'      => 'TCGA-EW-A1OX',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 65,
                'stage_num'               => 2,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.11,
                'buffa_hypoxia_score'     => -2.12,
                'ragnum_hypoxia_score'    => -1.78,
                'winter_hypoxia_score'    => -2.89,
            ],
            [
                'patient_identifier'      => 'TCGA-AC-A2QH',
                'er_status'               => false,
                'pr_status'               => false,
                'her2_binary'             => true,
                'age'                     => 43,
                'stage_num'               => 3,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => 0.44,
                'buffa_hypoxia_score'     => 2.89,
                'ragnum_hypoxia_score'    => 2.45,
                'winter_hypoxia_score'    => 3.34,
            ],
            [
                'patient_identifier'      => 'DZ-SKIKDA-011',
                'er_status'               => true,
                'pr_status'               => true,
                'her2_binary'             => false,
                'age'                     => 57,
                'stage_num'               => 1,
                'er_status_missing'       => false,
                'pr_status_missing'       => false,
                'fraction_genome_altered' => null,
                'buffa_hypoxia_score'     => null,
                'ragnum_hypoxia_score'    => null,
                'winter_hypoxia_score'    => null,
            ],
        ];
    }
}
